version: '3'

services:
  clearing-house-core-connector:
    image: yesayagm/clearing-house:core-connector
    container_name: coreconnector-container
    ports:
      - "8080:8080"

  clearing-app:
    image: yesayagm/clearing-house:clearing-app
    container_name: clearing-app-container
    ports:
      - "8081:8081"

  settlement-app:
    image: yesayagm/clearing-house:settlement-app
    container_name: settlement-app-container
    ports:
      - "8082:8082"

  logging-app:
    image: yesayagm/clearing-house:logging-app
    container_name: logging-app-container
    ports:
      - "8083:8083"

  claim-handling-app:
    image: yesayagm/clearing-house:claim-handling-app
    container_name: claim-handling-app-container
    ports:
      - "8084:8084"

  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
